name: covid19
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  csv:
  dio:
  flutter:
    sdk: flutter
  google_maps_flutter:
  http:
  implicitly_animated_reorderable_list:
  intl:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  google_maps_flutter:
    git:
      url: https://github.com/daohoangson/plugins.git
      ref: google_maps_flutter/heatmap
      path: packages/google_maps_flutter/google_maps_flutter
  google_maps_flutter_platform_interface:
    git:
      url: https://github.com/daohoangson/plugins.git
      ref: google_maps_flutter/heatmap
      path: packages/google_maps_flutter/google_maps_flutter_platform_interface

flutter:
  assets:
    - gosquared/flags/flags-iso/flat/32/
  uses-material-design: true
